version: '2.2.0.{build}'

shallow_clone: true

environment:
  ATK_ROOT: C:\projects\AudioTK
  ATK_OUT: C:\projects\ATK
  EIGEN_ROOT: C:\projects\Eigen
  FFTW_ROOT: C:\projects\fftw
  matrix:
    # 32 bits
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      BOOST_ROOT: C:/Libraries/boost_1_63_0
      FFTW_NAME: fftw-3.3.5-dll32.zip
      BITS: 32
      MSVC_PLATFORM: x86
      SHORT_MSVC_PLATFORM: x86
      COMPILER: Visual Studio 14 2015
      OUTPUT: static-x86
      ADDITONAL_CMAKE_FLAGS: "-DMSVC_RUNTIME=Static -DENABLE_SHARED_LIBRARIES=OFF -DENABLE_TESTS=OFF"
      VSINSTALL: "Microsoft Visual Studio 14.0\\VC"
      MSVC_VERSION: msvc-14.0

    # 64 bits
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      BOOST_ROOT: C:/Libraries/boost_1_63_0
      FFTW_NAME: fftw-3.3.5-dll64.zip
      BITS: 64
      MSVC_PLATFORM: amd64
      SHORT_MSVC_PLATFORM: x64
      COMPILER: Visual Studio 14 2015 Win64
      OUTPUT: static-x64
      ADDITONAL_CMAKE_FLAGS: "-DMSVC_RUNTIME=Static -DENABLE_SHARED_LIBRARIES=OFF -DENABLE_TESTS=OFF"
      VSINSTALL: "Microsoft Visual Studio 14.0\\VC"
      MSVC_VERSION: msvc-14.0

    # 32 bits
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      BOOST_ROOT: C:/Libraries/boost_1_63_0
      FFTW_NAME: fftw-3.3.5-dll32.zip
      BITS: 32
      MSVC_PLATFORM: x86
      SHORT_MSVC_PLATFORM: x86
      COMPILER: Visual Studio 14 2015 
      OUTPUT: dynamic-x86
      ADDITONAL_CMAKE_FLAGS:
      VSINSTALL: "Microsoft Visual Studio 14.0\\VC"
      MSVC_VERSION: msvc-14.0

    # 64 bits
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      BOOST_ROOT: C:/Libraries/boost_1_63_0
      FFTW_NAME: fftw-3.3.5-dll64.zip
      BITS: 64
      MSVC_PLATFORM: amd64
      SHORT_MSVC_PLATFORM: x64
      COMPILER: Visual Studio 14 2015 Win64
      OUTPUT: dynamic-x64
      ADDITONAL_CMAKE_FLAGS:
      VSINSTALL: "\\Microsoft Visual Studio 14.0\\VC"
      MSVC_VERSION: msvc-14.0

    # 32 bits
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      BOOST_ROOT: C:/Libraries/boost_1_64_0
      FFTW_NAME: fftw-3.3.5-dll32.zip
      BITS: 32
      MSVC_PLATFORM: x86
      SHORT_MSVC_PLATFORM: x86
      COMPILER: Visual Studio 15 2017
      OUTPUT: static-x86
      ADDITONAL_CMAKE_FLAGS: "-DMSVC_RUNTIME=Static -DENABLE_SHARED_LIBRARIES=OFF -DENABLE_TESTS=OFF"
      VSINSTALL: "Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build"
      MSVC_VERSION: msvc-14.1

    # 64 bits
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      BOOST_ROOT: C:/Libraries/boost_1_64_0
      FFTW_NAME: fftw-3.3.5-dll64.zip
      BITS: 64
      MSVC_PLATFORM: amd64
      SHORT_MSVC_PLATFORM: x64
      COMPILER: Visual Studio 15 2017 Win64
      OUTPUT: static-x64
      ADDITONAL_CMAKE_FLAGS: "-DMSVC_RUNTIME=Static -DENABLE_SHARED_LIBRARIES=OFF -DENABLE_TESTS=OFF"
      VSINSTALL: "Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build"
      MSVC_VERSION: msvc-14.1

    # 32 bits
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      BOOST_ROOT: C:/Libraries/boost_1_64_0
      FFTW_NAME: fftw-3.3.5-dll32.zip
      BITS: 32
      MSVC_PLATFORM: x86
      SHORT_MSVC_PLATFORM: x86
      COMPILER: Visual Studio 15 2017 
      OUTPUT: dynamic-x86
      ADDITONAL_CMAKE_FLAGS:
      VSINSTALL: "Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build"
      MSVC_VERSION: msvc-14.1

    # 64 bits
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      BOOST_ROOT: C:/Libraries/boost_1_64_0
      FFTW_NAME: fftw-3.3.5-dll64.zip
      BITS: 64
      MSVC_PLATFORM: amd64
      SHORT_MSVC_PLATFORM: x64
      COMPILER: Visual Studio 15 2017 Win64
      OUTPUT: dynamic-x64
      ADDITONAL_CMAKE_FLAGS:
      VSINSTALL: "Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build"
      MSVC_VERSION: msvc-14.1
   
matrix:
  allow_failures:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

init:
  - cmake --version
  - C:\"Program Files (x86)"\"%VSINSTALL%"\vcvarsall.bat %MSVC_PLATFORM%

before_build:
  - mkdir -p %FFTW_ROOT%
  - cd %FFTW_ROOT%
  - ps: wget ftp://ftp.fftw.org/pub/fftw/$env:FFTW_NAME -OutFile $env:FFTW_NAME
  - 7z x %FFTW_NAME%
  - ps: lib /machine:$env:SHORT_MSVC_PLATFORM /def:libfftw3-3.def
  - ps: lib /machine:$env:SHORT_MSVC_PLATFORM /def:libfftw3f-3.def
  - mkdir -p %EIGEN_ROOT%
  - cd %EIGEN_ROOT%
  - ps: wget http://bitbucket.org/eigen/eigen/get/3.3.3.zip -OutFile eigen.zip
  - 7z x eigen.zip
  - dir %ATK_ROOT%
  - cd %ATK_ROOT%
  - mkdir build
  - cd build
  - cmake -G "%COMPILER%" %ADDITONAL_CMAKE_FLAGS% -DENABLE_PYTHON=ON -DENABLE_GPL=ON -DBOOST_ROOT=%BOOST_ROOT% -DCMAKE_INSTALL_PREFIX=%ATK_OUT% -DFFTW_INCLUDES=%FFTW_ROOT% -DFFTW_LIBRARY_FFTW3=%FFTW_ROOT%\libfftw3-3.lib -DFFTW_LIBRARY_FFTW3F=%FFTW_ROOT%\libfftw3f-3.lib -DEIGEN_ROOT=%EIGEN_ROOT% -DENABLE_STATIC_LIBRARIES=ON ..

build_script:
  - msbuild INSTALL.vcxproj /property:Configuration=Release

after_build:
  - cd %ATK_OUT%
  - 7z a %ATK_ROOT%\AudioTK.%MSVC_VERSION%.%OUTPUT%.zip * -tzip

test_script:
  - set PATH=%ATK_OUT%\bin;%BOOST_ROOT%\lib%BITS%-%MSVC_VERSION%;%FFTW_ROOT%;%PATH%
  - set PYTHONPATH=%ATK_OUT%\lib\site-packages:%PYTHONPATH%
  - cd %ATK_ROOT%\build
  - set CTEST_OUTPUT_ON_FAILURE=True
  - msbuild RUN_TESTS.vcxproj /property:Configuration=Release

artifacts: 
  - path: AudioTK.%MSVC_VERSION%.%OUTPUT%.zip
    name: package

deploy:
  provider: GitHub
  description: 'Audio Toolkit files'
  auth_token:
    secure: jkxOmoTMtVlBIlIlVlxiGzV+4AX9NMjfT0hzTS3JxNtjGken02XG0FaDESBDxS0+
  artifact: package
  on:
    appveyor_repo_tag: true
