os: Visual Studio 2015
version: '1.5.{build}'

shallow_clone: true

environment:
  ATK_ROOT: c:\projects\AudioTK
  ATK_OUT: c:\projects\ATK
  EIGEN_ROOT: c:\projects\Eigen
  BOOST_ROOT: C:\Libraries\boost_1_63_0
  FFTW_ROOT: c:\projects\fftw
  PLATFORM: MSVC
  matrix:
    # 32 bits
    - FFTW_NAME: fftw-3.3.5-dll32.zip
      BITS: 32
      MSVC_PLATFORM: x86
      SHORT_MSVC_PLATFORM: x86
      COMPILER: Visual Studio 14 2015
      OUTPUT: static-x86
      ADDITONAL_CMAKE_FLAGS: "-DENABLE_STATIC_LIBRARIES=On -DMSVC_RUNTIME=Static -DENABLE_SHARED_LIBRARIES=Off -DENABLE_TESTS=Off"

    # 64 bits
    - FFTW_NAME: fftw-3.3.5-dll64.zip
      BITS: 64
      MSVC_PLATFORM: amd64
      SHORT_MSVC_PLATFORM: x64
      COMPILER: Visual Studio 14 2015 Win64
      OUTPUT: static-x64
      ADDITONAL_CMAKE_FLAGS: "-DENABLE_STATIC_LIBRARIES=On -DMSVC_RUNTIME=Static -DENABLE_SHARED_LIBRARIES=Off -DENABLE_TESTS=Off"

    # 32 bits
    - FFTW_NAME: fftw-3.3.5-dll32.zip
      BITS: 32
      MSVC_PLATFORM: x86
      SHORT_MSVC_PLATFORM: x86
      COMPILER: Visual Studio 14 2015 
      OUTPUT: dynamic-x86
      ADDITONAL_CMAKE_FLAGS: "-DENABLE_STATIC_LIBRARIES=On"

    # 64 bits
    - FFTW_NAME: fftw-3.3.5-dll64.zip
      BITS: 64
      MSVC_PLATFORM: amd64
      SHORT_MSVC_PLATFORM: x64
      COMPILER: Visual Studio 14 2015 Win64
      OUTPUT: dynamic-x64
      ADDITONAL_CMAKE_FLAGS: "-DENABLE_STATIC_LIBRARIES=On"

init:
  - cmake --version
  - C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\VC\vcvarsall.bat %MSVC_PLATFORM%
  
before_build:
  - mkdir -p %FFTW_ROOT%
  - cd %FFTW_ROOT%
  - ps: wget ftp://ftp.fftw.org/pub/fftw/$env:FFTW_NAME -OutFile $env:FFTW_NAME
  - 7z x %FFTW_NAME%
  - ps: lib /machine:$env:SHORT_MSVC_PLATFORM /def:libfftw3-3.def
  - ps: lib /machine:$env:SHORT_MSVC_PLATFORM /def:libfftw3f-3.def
  - mkdir -p %EIGEN_ROOT%
  - cd %EIGEN_ROOT%
  - ps: wget http://bitbucket.org/eigen/eigen/get/3.3.3.zip -OutFile eigen.zip
  - 7z x eigen.zip
  - cd %ATK_ROOT%
  - mkdir build
  - cd build
  - cmake -G "%COMPILER%" %ADDITONAL_CMAKE_FLAGS% -DBOOST_ROOT=%BOOST_ROOT% -DCMAKE_INSTALL_PREFIX=%ATK_OUT% -DFFTW_INCLUDES=%FFTW_ROOT% -DFFTW_LIBRARY_FFTW3=%FFTW_ROOT%\libfftw3-3.lib -DFFTW_LIBRARY_FFTW3F=%FFTW_ROOT%\libfftw3f-3.lib -DEIGEN_INCLUDE_DIRS=%EIGEN_ROOT% ..

build_script:
  - msbuild INSTALL.vcxproj /property:Configuration=Release

after_build:
  - cd %ATK_OUT%
  - 7z a c:\projects\AudioTK.%PLATFORM%.%OUTPUT%.zip * -tzip

test_script:
  - set PATH=%ATK_OUT%\bin;%BOOST_ROOT%\lib%BITS%-msvc-14.0;%FFTW_ROOT%;%PATH%
  - cd %ATK_ROOT%\build
  - set CTEST_OUTPUT_ON_FAILURE=True
  - msbuild RUN_TESTS.vcxproj /property:Configuration=Release

deploy:
  provider: GitHub
  auth_token:
    secure: ilhQ9vSyOl+QjRiRebj7CuQPYY1OygH3YxEuuFOXVa1cN4iw5yid2igEScLfKB5Xn2x2jMYDqL4bC6nLMHa1GNtCTIhCJrrHhXPeYX1W1EsOtExfAbD1G0QvUoQPZEBnK1Lu2Uf+qiQaH1IEquhzux8dxRCe/qJJzpntoWiLgm6po1giUAyQGsVzKlon4dxhgq08QcYxaQq2snOcKFJVx+zfeELfB7RZeEQXymtlMosMWnoKv3tjtFI5crWWdjD8oYKaTdLEms5EmR/cXAoYZ8jkhW0mTn1j9Ww9gaN4f/AnIlZDyggsdxVsV77rW/Kh6qqUdRbWaAnnpDgozv/HNXkgrFpxNyevIiS/pfbiyIT1zqT+iy4N9ofuc8iWuXncom3tDK/aGU+KS693ZkeLkkOT+FhT3YnIwE7UHeRS/Lqn26FQXQ/u7stuYVxCTrGR+LsfOrQdxmkQVOKicbWlOkU0+JpccaoES+j7SSCGgUkO/5f8bFzTraEu5VCN9pTuMX7TIp8OwS7b13L/TZGPwoeJDBtn5SsUl/1cqpuJbjQvf0KQqp6tJcQ8LjS9K0WrtVB+T2coQC5vYz5pM4RhYcGavj6a9+RM6U13PDvpHgP5ec5zeGbNJ2QKHLZ8s0LiuSMgffhp0vsl8E0nWjpelnSIDPtCLv5xAtk47vn+aiQ=
  artifact: c:\projects\AudioTK.%PLATFORM%.%OUTPUT%.tar.gz
  on:
    appveyor_repo_tag: true
