language: cpp
sudo: required

compiler:
  - clang
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - pwd
  - make

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libfftw3-dev