sudo: required
dist: precise
language: cpp

compiler:
  - gcc-5
  - gcc-6
  - clang-3.6
  - clang-3.7

before_install:
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get update -qq
  - sudo apt-get install libboost-test1.55-dev libboost-system1.55-dev libboost-timer1.55-dev libfftw3-dev libeigen3-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - pwd
  - make
