sudo: required
dist: precise
language: cpp

matrix:
   include:
     - compiler: gcc
       addons:
         apt:
           sources:
             - ubuntu-toolchain-r-test
           packages:
             - g++-5 libfftw3-dev libeigen3-dev
       env: COMPILER=g++-5
     - compiler: gcc
       addons:
         apt:
           sources:
             - ubuntu-toolchain-r-test
           packages:
             - g++-6 libfftw3-dev libeigen3-dev
       env: COMPILER=g++-6
     - compiler: clang-3.8
       addons:
         apt:
           sources:
             - ubuntu-toolchain-r-test
             - llvm-toolchain-precise-3.8
           packages:
             - clang-3.8 g++-6 libfftw3-dev libeigen3-dev
       env:
         - COMPILER=clang++-3.8
     - compiler: clang-3.9
       addons:
         apt:
           sources:
             - ubuntu-toolchain-r-test
             - llvm-toolchain-precise-3.9
           packages:
             - clang-3.9 g++-6 libfftw3-dev libeigen3-dev
       env:
         - COMPILER=clang++-3.9

before_install:
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get update -qq
  - sudo apt-get install libboost-test1.55-dev libboost-system1.55-dev libboost-timer1.55-dev

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER ..

script:
  - pwd
  - make
  - make test

